CREATE TABLE Animal(
   IdAnimal INT AUTO_INCREMENT PRIMARY KEY,
   Libelle VARCHAR(50)  NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Sexe(
   IdSexe INT AUTO_INCREMENT PRIMARY KEY,
   Libelle VARCHAR(1)  NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Personne(
   IdPersonne INT AUTO_INCREMENT PRIMARY KEY,
   Nom VARCHAR(50)  NOT NULL,
   IdSexe INT NOT NULL,
   FOREIGN KEY(IdSexe) REFERENCES Sexe(IdSexe)
)ENGINE=InnoDB;

CREATE TABLE Adoption(
   IdAdoption INT AUTO_INCREMENT PRIMARY KEY,
   IdPersonne INT,
   IdAnimal INT,
   FOREIGN KEY(IdPersonne) REFERENCES Personne(IdPersonne),
   FOREIGN KEY(IdAnimal) REFERENCES Animal(IdAnimal)
)ENGINE=InnoDB;
